version: "3.9"

services:
  develop:
    init: true
    environment:
      DISPLAY:
    build: 
      context: .
      dockerfile: Dockerfile
    user: 0:0
    #image: ghcr.io/kf8eez/wjstx
    image: wsjtx:newver
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "$PWD:/opt/project"
      - "$PWD/config:/root/.config"
      - "$PWD/log:/root/.local/share"
    network_mode: "host"
    devices:
      #- "/dev/ttyUSB0:/dev/ttyUSB0"
      #- "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/snd:/dev/snd"
     
    privileged: true
    command:
      - /bin/bash
    working_dir: /opt/project
